import { Categories, Product } from "../../type.t";
import categoryMakis from "../assets/cat-makis.png";
import categoryAlitas from "../assets/cat-alitas.png";
import categoryEntradas from "../assets/cat-entradas.png";
import categoryEspeciales from "../assets/cat-especiales.png";
import combo_comelon from "../assets/combo_comelon.webp";
import gran_combo from "../assets/gran_combo.webp";
import full_comelon from "../assets/full_comelon.webp";
import como_maki from "../assets/como_maki.webp";
import medio_personal from "../assets/medio_personal.webp";
import personal from "../assets/personal.webp";
import d_todito from "../assets/d_todito.webp";
import familar from "../assets/familar.webp";
import combo_sushi from "../assets/combo_sushi.png";
import acevichado from "../assets/acevichado_roll.webp";
import alaska_roll from "../assets/alaska_roll.webp";
import alaska_roll_especial from "../assets/alaska_roll_especial.webp";
import tropical_roll from "../assets/tropical_roll.webp";
import california from "../assets/california.webp";
import leche_tigre from "../assets/leche_tigre.webp";

export const makis = [
  {
    id: 1,
    name: "Maki Acevichado",
    price: 20,
    priceTotal: 21,
    image: acevichado,
    description:
      "Relleno de pescado, empanizado (crocante) y palta, cubierto de finas láminas de atun fresco bañado en salsa acevichada y togarashi",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 2,
    name: "Alaska Roll",
    price: 20,
    priceTotal: 21,
    image: alaska_roll,
    description:
      "Maki relleno de salmon fresco, queso crema y palta toppig de cesamo (ajonjoli).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 3,
    name: "Alaska Roll Especial",
    price: 20,
    priceTotal: 21,
    image: alaska_roll_especial,
    description:
      "Maki relleno de salmon fresco, queso crema y palta toppig de palta y salmon fresco con ensalada de wakame.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 4,
    name: "Tropical Roll",
    price: 20,
    priceTotal: 21,
    image: tropical_roll,
    description:
      "Maki relleno de pescado apanado “crocante” queso crema y palta. topping de platano frito, bañado en salsa tarek (salsa de anguila).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 5,
    name: "California Roll",
    price: 20,
    priceTotal: 21,
    image: california,
    description:
      "Maki relleno de palitos de cangrejo (kanikama), palta y cebolla china. topping de cesamo (ajonjoli) y tongarashi",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 6,
    name: "Leche de tigre",
    price: 20,
    priceTotal: 21,
    image: leche_tigre,
    description:
      "Relleno de pescado fresco y palta, topping de chicharron de pescado “crocante”, bañado en leche de tigre",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 7,
    name: "Spicy Tuna",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de atún con cebolla china y siracha súper picante topping de atún.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 8,
    name: "Maki Home",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno con pepino, cebolla china, atún y salmón, pescadito apanado, alga por fuera, topping de wakame.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 9,
    name: "Vegetariano Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description: "Relleno de zanahoria cebolla china y pepino topping de palta",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 10,
    name: "Maki Sakura",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Rellenos de vegetales tempura topping de chicharron de pescado (crocante) bañado en mayonesa siracha y tarek (toques picantes)",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 11,
    name: "Avocado Maki",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Pescado furay, queso crema, topping de palta y ajonjolí (salsa tarek).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 12,
    name: "Anti-Cuchero Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado “crocante” y palta, topping de pescado fresco, salsa anticuchera “flameado”",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 13,
    name: "Maki Dragon",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado apanado crocante pepino topping de aguacate con salsa dragón (picante) y anguila.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 14,
    name: "Chimi-Churri Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de palta, queso crema y cebolla china, topping de pescado fresco con chimi churry “flameado”",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 15,
    name: "Fuji Maki",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado crocantes, cebollin. topping de pescado crocante con salsa fuji (miel mostaza)",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 16,
    name: "Pasión Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de canimama, pepino, topping de salmon flameado y tiras de limon.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 17,
    name: "Roca Maki",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de palta y pescado furay, topping de trucha salmonada, salsa dragon y queso parmesano flameado.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 18,
    name: "KIMBAP",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pepino, lechuga, tortilla de huevo, zanahoria, espinaca y hot dog.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 19,
    name: "Sunset Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de atún, queso crema y pata, topping de atún, palta y tiras de canicama.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 20,
    name: "Salmon Skin Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de piel de salmon crocante, queso crema, palta, topping de ajonjoli y salsa tarek",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 21,
    name: "Terik Maki",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pollo crocante, cebolla china, topping de pollo crocante, bañado en salsa teriyaki",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 22,
    name: "Maki Cheese Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado fresco, palta, topping de platano frito, queso amarillo flameado con salsa tarek",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 23,
    name: "Arcoiris Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado fresco, kanikama, pepino, topping de salmon, atun, palta y wakame.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 24,
    name: "Crazzy Mango",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado furay y mango, topping de ajonjoli, salsa fuji, flameado.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 25,
    name: "Platano Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Maki tempurizado, envuelto en platano frito relleno de palta queso crema y pescado fresco. bañado en salsa tarek (salsa de angila).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 26,
    name: "Tiger Roll Especial",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Maki tempurizado en hojuelas de maiz , relleno de pescado, palta y queso crema, topping de ensalada neptuno. bañado en salsa tarek.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 27,
    name: "Furay Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Maki Relleno de pescado apanado ”crocante” queso crema y palta. bañado en salsa tarek (salsa de anguila).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 28,
    name: "Pasific Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Maki tempurizado en hojuelas de maiz , relleno de atun fresco, cebollin y queso crema. bañado en salsa tarek (salsa de anguila).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 29,
    name: "Tokio Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Relleno de pescado apanado “crocante”, queso crema, cebollín apanado (frito) toppin de pescado crocante, salsa de anguila y salsa dragón",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
  {
    id: 30,
    name: "Tiger Roll",
    price: 20,
    priceTotal: 21,
    image: medio_personal,
    description:
      "Maki tempurizad, relleno de pescado fresco, palta y queso crema, bañado en salsa tarek (salsa de anguila).",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Makis",
    container: 1,
  },
];
export const alitas = [
  {
    id: 300,
    name: "Alitas BBQ",
    price: 15,
    priceTotal: 15.5,
    image: acevichado,
    description:
      "Alitas de pollo bañadas en salsa BBQ, acompañadas de papas fritas.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Alitas",
    container: 0.5,
  },
  {
    id: 301,
    name: "Alitas Bufalo",
    price: 15,
    priceTotal: 15.5,
    image: acevichado,
    description:
      "Alitas de pollo bañadas en salsa BBQ Bufalo (Picante), acompañadas de papas fritas.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Alitas",
    container: 0.5,
  },
  {
    id: 302,
    name: "Alitas Acevichadas",
    price: 15,
    priceTotal: 15.5,
    image: acevichado,
    description:
      "Alitas de pollo bañadas en salsa acevichada, acompañadas de papas fritas.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Alitas",
    container: 0.5,
  },
  {
    id: 303,
    name: "Alitas Nikkei",
    price: 15,
    priceTotal: 15.5,
    image: acevichado,
    description:
      "Alitas de pollo bañadas en salsa Nikkei, acompañadas de papas fritas.",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "Alitas",
    container: 0.5,
  },
];
export const bebidas = [
  {
    id: 600,
    name: "Pepsi personal",
    price: 2,
    priceTotal: 2,
    image: acevichado,
    description: "Pepsi de 355ml",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "bebidas",
    container: 0,
  },
  {
    id: 601,
    name: "Piña personal",
    price: 2,
    priceTotal: 2,
    image: acevichado,
    description: "Piña de 355ml",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "bebidas",
    container: 0,
  },
  {
    id: 602,
    name: "Naranja personal",
    price: 2,
    priceTotal: 2,
    image: acevichado,
    description: "Naranja de 355ml",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "bebidas",
    container: 0,
  },
  {
    id: 603,
    name: "7up personal",
    price: 2,
    priceTotal: 2,
    image: acevichado,
    description: "7up de 355ml",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "bebidas",
    container: 0,
  },
  {
    id: 604,
    name: "Agua personal",
    price: 2,
    priceTotal: 2,
    image: acevichado,
    description: "Agua de 355ml",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "bebidas",
    container: 0,
  },
];
export const adicionales = [
  {
    id: 700,
    name: "Salsa Acevichada",
    price: 1,
    priceTotal: 1,
    image: acevichado,
    description: "Salsa Acevichada",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "adicional",
    container: 0,
  },
  {
    id: 701,
    name: "Salsa Anguila (Tarek)",
    price: 1,
    priceTotal: 1,
    image: acevichado,
    description: "Salsa Anguila (Tarek)",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "adicional",
    container: 0,
  },
  {
    id: 702,
    name: "Salsa Dragón (Picante)",
    price: 1,
    priceTotal: 1,
    image: acevichado,
    description: "Salasa Dragón (Picante)",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "adicional",
    container: 0,
  },
  {
    id: 703,
    name: "Palillos desechables",
    price: 1,
    priceTotal: 1,
    image: acevichado,
    description: "Palillos desechables",
    amountDrinks: 0,
    amountSushi: 0,
    amountWings: 0,
    category: "adicional",
    container: 0,
  },
];
export const combos = [
  {
    id: 400,
    name: "1/2 Personal",
    price: 18,
    priceTotal: 19.5,
    image: medio_personal,
    description: "5 piezas de maki + 2 alitas + gaseosa 355ml",
    amountDrinks: 1,
    amountSushi: 1,
    amountWings: 1,
    category: "Combos",
    container: 1.5,
  },
  {
    id: 401,
    name: "Personal",
    price: 25,
    priceTotal: 26.5,
    image: personal,
    description: "10 piezas de maki + 3 alitas + gaseosa 355ml",
    amountDrinks: 1,
    amountSushi: 2,
    amountWings: 1,
    category: "Combos",
    container: 1.5,
  },
  {
    id: 402,
    name: "Comelon",
    price: 35,
    priceTotal: 37,
    image: combo_comelon,
    description: "20 piezas de maki + gaseosa 355ml",
    amountDrinks: 1,
    amountSushi: 2,
    amountWings: 0,
    category: "Combos",
    container: 2,
  },
  {
    id: 403,
    name: "Full Comelon",
    price: 40,
    priceTotal: 42.5,
    image: full_comelon,
    description: "20 piezas de maki + 3 alitas + gaseosa 355ml",
    amountDrinks: 1,
    amountSushi: 2,
    amountWings: 1,
    category: "Combos",
    container: 2.5,
  },
  {
    id: 404,
    name: "Full Makis",
    price: 55,
    priceTotal: 59,
    image: como_maki,
    description: "40 piezas de maki + 2 gaseosa 355ml",
    amountDrinks: 2,
    amountSushi: 4,
    amountWings: 0,
    category: "Combos",
    container: 4,
  },
  {
    id: 405,
    name: "Gran Combo",
    price: 65,
    priceTotal: 70,
    image: gran_combo,
    description: "40 piezas de maki + 6 alitas + 2 gaseosa 355ml",
    amountDrinks: 2,
    amountSushi: 4,
    amountWings: 2,
    category: "Combos",
    container: 5,
  },
  {
    id: 406,
    name: "Familiar",
    price: 85,
    priceTotal: 92,
    image: familar,
    description: "60 piezas de maki + 8 alitas + 1 gaseosa 1.5Lt.",
    amountDrinks: 1,
    amountSushi: 6,
    amountWings: 2,
    category: "Combos",
    container: 7,
  },
  {
    id: 407,
    name: "D'Todito",
    price: 35,
    priceTotal: 37.5,
    image: d_todito,
    description:
      "5 piezas de makis + 1/2 poke bow + 2 Eby Furay + 2 siu mai + 2 gyosas + 2 niguiris + 2 alitas+ 2 croquetas + 1 gaseosa 355ml",
    amountDrinks: 1,
    amountSushi: 1,
    amountWings: 1,
    category: "Combos",
    container: 2.5,
  },
];
export const products: Product[] = [
  ...makis,
  ...alitas,
  ...bebidas,
  ...adicionales,
  ...combos,
];
export const categories: Categories[] = [
  {
    id: 1,
    name: "Combos",
    image: combo_sushi,
  },
  {
    id: 2,
    name: "Makis",
    image: categoryMakis,
  },
  {
    id: 3,
    name: "Alitas",
    image: categoryAlitas,
  },
  {
    id: 4,
    name: "Entradas",
    image: categoryEntradas,
  },
  {
    id: 5,
    name: "Especiales",
    image: categoryEspeciales,
  },
];
